version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3003:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./data/sqlite:/data/sqlite  # 添加SQLite数据库文件的挂载
    environment:
      - SQL_DSN=sqlite3:/data/sqlite/new-api.db  # 修改为SQLite的连接字符串
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

# volumes:
  # mysql_data: # 删除 MySQL 数据卷
